### ISSUE TITLE
Suggestion - Unlock DB just after mongodump command completes

### ISSUE THREAD

**Issue by iokobi** [sysboss/mongodb_backup#1]
Hello,
Thanks for this awesome script. Gets the job done.

Just a suggestion in form of a question; 
Would is not be preferable to move the fsyncUnlock to just after the mongodump command completes?

Waiting till after compression and upload have been completed would lead to longer lock times especially for very large DBs.

Your thoughts?

**Comment by sysboss** [comment]
@iokobi thanks for your suggestion. You are definitely right.
I've added a fix for this issue; it should no longer be a problem.
